# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY, $AWS_DEFAULT_REGION setup in the Repository variables and Deployment variables.
image:
  name: 657799620713.dkr.ecr.us-east-1.amazonaws.com/node-alpine:latest
  aws:
    access-key: $AWS_ACCESS_KEY_ID
    secret-key: $AWS_SECRET_ACCESS_KEY

# Workflow Configuration
pipelines:
  branches:
    master:
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            - npm install -g aws-cdk
            - cd document-pipeline
            - npm ci
            - npm run build
            - cdk deploy --require-approval never
