#  Template AWS Cloudformation deploy

#  This template allows you to deploy your configuration as code using AWS CloudFormation.
#  The workflow allows validate, linting and security scans on feature branches (as well as master).
#  The AWS cloudformation template will be validated and deployed after the code is merged to master.

# Prerequisites: $AWS_ACCESS_KEY_ID, $AWS_SECRET_ACCESS_KEY, $AWS_DEFAULT_REGION setup in the Repository variables and Deployment variables.
# For advanced cases, please, follow examples from the pipe's README https://bitbucket.org/atlassian/aws-cloudformation-deploy/src/master/README.md
# You can find AWS Cloudformation template example for creating AWS S3 Bucket in the template.yaml file.
# You can modify and use it to deploy any of your configuration as code. https://aws.amazon.com/cloudformation/resources/templates/

image: atlassian/default-image:2

# Workflow Configuration

pipelines:
  branches:
    master:
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          image: node:alpine
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            - npm install -g aws-cdk
            - cd document-pipeline
            - npm ci
            - npm run build
            - cdk deploy --require-approval never
